name: 'pkldoc-action'
author: 'Emily McLean'
description: 'Generates PklDoc for a Pkl module.'
inputs:
  input-files:
    description: 'The Pkl files to process, separated by commas.'
    required: true
  output-folder:
    description: 'Where the resulting data will be written to.'
    required: true
  pkl-version:
    description: The pkl version to install.
    required: false
    default: '0.30.2'
runs:
  using: 'composite'
  steps:
    - run: |
        IFS=',' read -ra args <<< "${{ inputs.input-files }}"

        input_files=()
        for file in "${args[@]}"; do
            input_files+=("/data/$(echo "$file" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')")
        done

        docker run --rm -v "./:/data" ghcr.io/emilymclean/pkl-codegen-doc:${{ inputs.pkl-version }}-1 "${input_files[@]}" -o "/data/${{ inputs.output-folder }}"
      shell: bash
branding:
  icon: 'cpu'
  color: 'green'